Normalized dynamic hook names coalesce to array
ERROR: PossiblyInvalidArgument - Plugin.php:551:30 - Argument 1 of ltrim
expects string, but possibly different type
array<array-key, string>|string provided
(see https://psalm.dev/092)